skip_on_cran()
skip_if_offline()

test_that("install_r4np installs packages", {
  # Run the function
  install_r4np()

  # Check that the packages were installed
  expect_true(requireNamespace("broom", quietly = TRUE))
  expect_true(requireNamespace("car", quietly = TRUE))
  expect_true(requireNamespace("correlation", quietly = TRUE))
  expect_true(requireNamespace("effectsize", quietly = TRUE))
  expect_true(requireNamespace("exact2x2", quietly = TRUE))
  expect_true(requireNamespace("ggdist", quietly = TRUE))
  expect_true(requireNamespace("ggforce", quietly = TRUE))
  expect_true(requireNamespace("ggmosaic", quietly = TRUE))
  expect_true(requireNamespace("ggraph", quietly = TRUE))
  expect_true(requireNamespace("ggridges", quietly = TRUE))
  expect_true(requireNamespace("janitor", quietly = TRUE))
  expect_true(requireNamespace("jtools", quietly = TRUE))
  expect_true(requireNamespace("lavaan", quietly = TRUE))
  expect_true(requireNamespace("lubridate", quietly = TRUE))
  expect_true(requireNamespace("igraph", quietly = TRUE))
  expect_true(requireNamespace("mice", quietly = TRUE))
  expect_true(requireNamespace("mi", quietly = TRUE))
  expect_true(requireNamespace("modelr", quietly = TRUE))
  expect_true(requireNamespace("naniar", quietly = TRUE))
  expect_true(requireNamespace("parameters", quietly = TRUE))
  expect_true(requireNamespace("patchwork", quietly = TRUE))
  expect_true(requireNamespace("performance", quietly = TRUE))
  expect_true(requireNamespace("psych", quietly = TRUE))
  expect_true(requireNamespace("pwr", quietly = TRUE))
  expect_true(requireNamespace("rcompanion", quietly = TRUE))
  expect_true(requireNamespace("rstatix", quietly = TRUE))
  expect_true(requireNamespace("scales", quietly = TRUE))
  expect_true(requireNamespace("see", quietly = TRUE))
  expect_true(requireNamespace("simputation", quietly = TRUE))
  expect_true(requireNamespace("skimr", quietly = TRUE))
  expect_true(requireNamespace("tidytext", quietly = TRUE))
  expect_true(requireNamespace("tidyverse", quietly = TRUE))
  expect_true(requireNamespace("wesanderson", quietly = TRUE))
  expect_true(requireNamespace("wordcloud", quietly = TRUE))
})
